

SELECT SYS_CONTEXT('USERENV','CON_NAME') AS con_name FROM dual;

ALTER SESSION SET CONTAINER = XEPDB1;


SELECT tablespace_name FROM dba_tablespaces ORDER BY 1;

-- Si BIBLIOTECA_TBS NO existe en el PDB, créalo aquí mismo:
 CREATE BIGFILE TABLESPACE BIBLIOTECA_TBS
   DATAFILE 'C:\app\emanu\product\21c\oradata\XE\BIBLIOTECA_TBS001.dbf'  -- o ruta Linux
   SIZE 200M
  AUTOEXTEND ON NEXT 50M MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO;
  
 -- DROP TABLESPACE BIBLIOTECA_TBS;

CREATE USER BIBLIOTECA IDENTIFIED BY "TuPasswordFuerte#2025"
  DEFAULT TABLESPACE BIBLIOTECA_TBS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON BIBLIOTECA_TBS;

-- Privilegios mínimos para desarrollar
GRANT CREATE SESSION TO BIBLIOTECA;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER,
      CREATE PROCEDURE, CREATE SYNONYM TO BIBLIOTECA;

-- (Opcional) Para simplificar durante desarrollo:
-- GRANT UNLIMITED TABLESPACE TO BIBLIOTECA; -- si prefieres no manejar cuotas

